### ISSUE TITLE
Please provide an example of using JSAP for subscription

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA-js#2]
May I use JSAP to specify the SPARQL query to be used in a subscribe call?

**Comment by relu91** [comment]
Hi Luca, thank you for submitting. 

The example is right before of the end of readme. Look for the creation of a consumer. 

**Notice** you should use v0.1.0 to get it work with the latest SEPA release

**Comment by lroffia** [comment]
I would suggest to modify the JSAP as follows:

"simpleUpdate": {
			"sparql": "INSERT **DATA** { <hello> <from> <js> }"
		},
		"updateArgs": {
			"sparql": "INSERT **DATA** {?sub ?pred ?obj}",
			"forcedBindings": {
				"sub": {
					"type": "uri",
					"value": "hello"
				},
				"pred": {
					"type": "uri",
					"value": "from"
				},
				"obj": {
					"type": "literal",
					"value": "js"
				}
			}
		}

**Comment by relu91** [comment]
Can I close this issue?
