### ISSUE TITLE
Broken socket indication

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA-js#3]
It could be useful to provide an indication of a broken socket. The client could then try to connect again.

**Comment by relu91** [comment]
Sure, I'll totally consider it for the next version.

**Comment by relu91** [comment]
Version 0.6.0 introduces a new event API for subscriptions. The  `connection-error` event is related to a broken socket. I'll close the issue for now if in the future the `connection-error` event is not enough we should evaluate a specific event for broken sockets.
